---
- name: Check if EPEL repo is already configured
  ansible.builtin.stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile_result
  tags:
    - installEPEL

- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  tags:
    - installEPEL

- name: Install EPEL repo
  when: not epel_repofile_result.stat.exists
  ansible.builtin.dnf:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  tags:
    - installEPEL
