---
- name: Install Cockpit packages
  ansible.builtin.dnf:
    name: "{{ cockpit_packages }}"
    state: latest

- name: Enable Cockpit Socket
  ansible.builtin.service:
    name: cockpit.socket
    state: started
    enabled: yes

- name: Enable Cockpit on Firewalld
  ansible.posix.firewalld:
    service: cockpit
    state: enabled
    permanent: yes
  notify: restart firewalld

- name: Flush handlers - setup_cockpit
  ansible.builtin.meta: flush_handlers
